import json
import logging
from snakemake.utils import min_version

# ==== RUN ME through sbatch batchslurm.sh ====
# a version w cluster config is not yet available (may solve some of the issues w env)
min_version("8.11")

logging.basicConfig(
    filename="workflow.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)


# NOTE if the rules aren't chained only the first rule will be executed


rule solve:
    input:
        constraints="data/constraints_copy.json",
        license_file="/p/projects/rd3mod/gurobi_rc/gurobi.lic",
    output:
        "data/solution_test_run.json",
    threads: 1
    log:
        "logs/optimize.log",
    script:
        "scripts/optimise.py"


rule log_test:
    log:
        "logs/test.log",
    script:
        "scripts/test_log.py"
